[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_lab_cpi_guard = "<YOUR-PROGRAM-ID-HERE>"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/YOUR/PATH/HERE/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
